### ISSUE TITLE
Add function for user defined callbacks

### ISSUE THREAD

**Issue by artem-zinnatullin** [marzocchi/zsh-notify#10]
What about functions for callbacks if user want to add for example sound after notification?

I can make pull request if you don't mind

**Comment by marzocchi** [comment]
I never needed sounds so I never thought of it, but pull requests are certainly welcome, thank you!

**Comment by artem-zinnatullin** [comment]
Okay, I'll make PR on weekends, @marzocchi thank you for great plugin, I wondered about this thing for several years :+1:

**Comment by artem-zinnatullin** [comment]
@marzocchi you can assign this issue to me

**Comment by marzocchi** [comment]
@artem-zinnatullin for some reason it doesn't let me you as assignee

**Comment by artem-zinnatullin** [comment]
@marzocchi oh, I forgot that I must be in repo team, so never mind, I'll just make PR
