### ISSUE TITLE
$ZSH_NOTIFY_FOCUS_TERMINAL not work in linux mint

### ISSUE THREAD

**Issue by Ridermansb** [marzocchi/zsh-notify#19]
Even after set this variable to false, the `source .zshrc` and reopen the terminal, after run command, the terminal is opened.

I would just display the notification and do not open the terminal after finish the command.

    
    $ echo $ZSH_NOTIFY_FOCUS_TERMINAL
    false

**Comment by marzocchi** [comment]
thank you for the report @Ridermansb, let's ping @mehanoid as I don't have access to linux.

**Comment by mehanoid** [comment]
I suppose you are trying the latest git version? The terminal should not be opened by default unless you set this variable to true, it also can be undefined. Maybe it depends on DE or windows manager, which WM do you use?

**Comment by Ridermansb** [comment]
Linux Mint (Cinnamon).

**Comment by mehanoid** [comment]
I tried the Live CD and did not found that problem.
But you can try this branch:
https://github.com/mehanoid/zsh-notify/tree/disable_demanding_attention
and set environment variable:
export ZSH_NOTIFY_DEMAND_ATTENTION_TO_TERMINAL=false
