### ISSUE TITLE
Doesn't work for me.

### ISSUE THREAD

**Issue by wildeyes** [marzocchi/zsh-notify#21]
I'm getting `74:82: syntax error: Expected “,” but found identifier. (-2741)` after running every command, and although I'm using iTerm 2, it also outputs `No notifier program found.`.

**Comment by marzocchi** [comment]
does it work if you switch to the `next-iterm` branch?

**Comment by MathieuLorber** [comment]
I have the same problem since I updated to iterm2 build 3.0.0
Even with the next-iterm branch

**Comment by shobhitg** [comment]
I have the same issue. Has anyone found a solution yet?

**Comment by marzocchi** [comment]
Hi all, apparently I missed some iTerm2 updates!

Anyway, I just merged to master a commit that works fine with the iTerm2 beta I just downloaded (“About iTerm2” says: “Build 3.0.2”), can you give it a shot? Thanks.

**Comment by wildeyes** [comment]
Giving it a shot in the next few days.

**Comment by MathieuLorber** [comment]
Current master works again for me =)

**Comment by marzocchi** [comment]
Good! Thank you!

**Comment by elalemanyo** [comment]
master works great again!
Thanks.

**Comment by marzocchi** [comment]
good, thank you!

I'll close this issue (at least for the moment).

**Comment by kompiro** [comment]
@marzocchi I met same issue after upgraded to Build "3.0.4" from 2.X .

**Comment by kompiro** [comment]
I fix this error that commented out to source zsh-notify in `.zshrc`.
