### ISSUE TITLE
Getting mismatched tags error

### ISSUE THREAD

**Issue by mhartington** [marzocchi/zsh-notify#32]
Hi there! Sorry if this is the wrong place for this issue, not 100% sure where the issue is coming from.

This morning it seems that any time a notification is shown, an error is thrown. 

<details>
```
Entity: line 600: parser error : Opening and ending tag mismatch: property line 561 and class
    </class>
            ^
Entity: line 602: parser error : Opening and ending tag mismatch: class line 434 and suite
  </suite>
          ^
Entity: line 603: parser error : Opening and ending tag mismatch: suite line 227 and dictionary
</dictionary>
             ^
Entity: line 604: parser error : Premature end of data in tag dictionary line 4
```
</details>

ENV:

MacOS 10.12 beta 2
Iterm2 nightly Build 3.0.20160717-nightly

**Comment by marzocchi** [comment]
Hello! Seems like there's some major issue with iTerm2's AppleScript dictionary in the nightly, in fact it shows as empty in Script Editor, too.

![iterm 2016-07-17 21-51-50](https://cloud.githubusercontent.com/assets/291474/16902771/cf93a028-4c68-11e6-910b-e8d4e3ea759c.png)

I think your only option now is to revert to a previous nightly.

**Comment by mhartington** [comment]
Ahh, awesome. Thanks for the reply!
