### ISSUE TITLE
"No notifier program found" on OS X Sierra

### ISSUE THREAD

**Issue by unixorn** [marzocchi/zsh-notify#37]
on OS X Sierra I'm getting an error

```
$ sleep 60
$ No notifier program found.
```

It doesn't matter if I'm using iTerm 2 v3 or the native Terminal.app.

I'll check Monday if this happens on 10.11 too.

**Comment by marzocchi** [comment]
message ain't particularly clear, but I suspect installing Sierra ate your terminal-notifier.app. [Find it here](https://github.com/alloy/terminal-notifier).

Or maybe it's just no longer available in $PATH.

**Comment by marzocchi** [comment]
As a side note, use this to make testing quicker (you won't need to wait 60 seconds, an eternity ;-))

```
zstyle ':notify:*' command-complete-timeout 2
```

**Comment by unixorn** [comment]
My bad. I refreshed brew recently and must have forgotten to add the notifier, so when I re-added zsh-notify to my plugins list it couldn't find it.
