### ISSUE TITLE
No works on Wayland

### ISSUE THREAD

**Issue by simonbcn** [marzocchi/zsh-notify#43]
Arch Linux 64 bits

```
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)   
xdo_get_active_window reported an error
```

`xdotool` is a X.org command and it doesn't work on Wayland.

**Comment by marzocchi** [comment]
Thank you for your report! 

I don't use linux so I can't investigate much, [no alternative is available](http://superuser.com/a/1032426), right?
