### ISSUE TITLE
notify-if-background:46: parse error near `]]'

### ISSUE THREAD

**Issue by frdmn** [marzocchi/zsh-notify#9]
Hey,

i'm trying to get the `next-iterm` branch working for me, but as soon as I interrupt a command (CTRL + C) I get the follwing message:

    notify-if-background:46: parse error near `]]'

Using, ZSH and iTerm Build 2.9.20150128-nightly

Any ideas?

**Comment by marzocchi** [comment]
Hi @frdmn! I cannot reproduce the issue with latest iTerm nightly and zsh 5.0.7. Seems more like a shell issue than an iTerm related one. Which version of zsh are you using?

**Comment by frdmn** [comment]
@marzocchi Strange. I just got rid of my `.zshrc` and tried with a clean (or empty) configuration, same results:

    mbp% zsh --version
    zsh 5.0.5 (x86_64-apple-darwin14.0)
    mbp% source /usr/local/src/zsh-notify/notify.plugin.zsh
    mbp%

I try to get my hands on the 5.0.7 version of zsh and will report back. :)

**Comment by frdmn** [comment]
@marzocchi Nope, I can't get it to work. Same issue with 5.0.7:

    ➜  ~  zsh --version
    zsh 5.0.7 (x86_64-apple-darwin14.0.0)
    ➜  ~
    notify-if-background:46: parse error near `]]'
    ➜  ~

I am really out of ideas right now.

**Comment by marzocchi** [comment]
@frdmn me too actually! 

Guess you are using the next-iterm branch (there is no `]]` on line 46 of notify-if-background on master). Is that file verbatim or does it have modifications?

**Comment by frdmn** [comment]
@marzocchi yeah, unaltered `notify-if-background` from the `next-iterm` branch:

http://hastebin.com/suvegaqava.xml

**Comment by marzocchi** [comment]
Thank you for the investigation @frdmn! I couldn't find a clear explanation of why the syntax is fine in my shell but not in yours in zsh's docs, but since `[[` expects a test, changing the expression to `[[ -n ${TMUX+1} ]]` should probably fix it. Care to test it and send me a pull request?

As for the AppleScript syntax error: these usually happen when using zsh-notify's master branch with a recent iTerm2 (the AppleScript dictionary changed). The next-iterm uses the current AppleScript syntax. I'm using it with next-2.9.20150130-nightly and it's working.

**Comment by frdmn** [comment]
@marzocchi There you go :)

Unfortunately, i still stuck with the AppleScript error below:

    ❯  zsh-notify git:(next-iterm) 39:46: syntax error: Expected “,” but found identifier. (-2741)

Also double checked that i'm using the correct branch.

**Comment by marzocchi** [comment]
@frdmn Thank you the pull request.

We need to find out what's going wrong with AppleScript. I think I had some problems with AS syntax when I had two different versions of iTerm2 installed. Can you check that?

Also, can you post what's the output of this:

     tell-iterm2 <<< "tty of (current session of current tab of current window) is equal to \"$TTY\""

`tell-iterm2` is a function defined by the plugin which sends AppleScript commands to iTerm2.

**Comment by frdmn** [comment]
@marzocchi If i try to execute it in the repo directory, i get the following errors:

    $ ./tell-iterm2 <<< "tty of (current session of current tab of current window) is equal to \"$TTY\""
    ./tell-iterm2: line 31: local: can only be used in a function
    ./tell-iterm2: line 32: typeset: -A: invalid option
    typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
    ./tell-iterm2: line 33: zparseopts: command not found
    ./tell-iterm2: line 37: syntax error near unexpected token `return'
    ./tell-iterm2: line 37: `if [[ $ret != 0 ]] return $ret'

Do I need to source anything first?

**Comment by marzocchi** [comment]
Ah! tell-iterm2 is a function definition file, meant to be used with zsh's autoload capabilities, you cannot execute it as a script (in fact, it should not even be executable).

You should just source `notify.plugin.zsh` and just invoke tell-iterm2 like in my previous comment from any directory.

**Comment by frdmn** [comment]
@marzocchi You are right, I had to add execution permissions for that. My bad. Here's what I get now:

    $ tell-iterm2 <<< "tty of (current session of current tab of current window) is equal to \"$TTY\""
    39:46: syntax error: Expected “,” but found identifier. (-2741)
    notify-if-background:46: parse error near `]]'

**Comment by marzocchi** [comment]
Sometimes they come back: `notify-if-background:46: parse error near `]]'` :)

But lets concentrate on the AppleScript error: the script you run is valid for iTerm2 nightlies, but not for older versions. Do you have more than one iTerm2 on your Mac? Maybe somewhere like the Download folder?

Besides, this is the script run by tell-iterm2. Does it work in Apple's Script Editor? Does it even compile?

    tell app "iTerm"
        activate
        tty of (current session of current tab of current window) is equal to "/dev/ttys000"
    end

**Comment by frdmn** [comment]
@marzocchi No, it doesn't compile:

![bildschirmfoto 2015-02-01 um 16 38 27](https://cloud.githubusercontent.com/assets/944459/5992605/c78c7520-aa30-11e4-958e-0b975ecd4aa7.png)

I also don't think that I have any older version of iTerm, but just as you said that, something came into my mind:

I used brew cask to install iTerm 2, so instead of it's usual location (/Applications), it's installed to /opt/homebrew-cask/Caskroom/iterm2-nightly/latest/iTerm.app and symlinked from there into /Applications.

Could that affect the AppleScript library catalogue?

**Comment by marzocchi** [comment]
Well, I have no experience with cask, but I'd guess that having different versions of /Application/iTerm.app over time might somehow confuse AppleScript. 

I'd try the following:

- remove any iTerm.app from the Caskroom 
- run a simple script like `tell app "iTerm" to activate` with Script Editor in order to get the "choose a dictionary" prompt and cancel it (getting no prompt would be a sign that there are other iTerm.app somewhere on your Mac);
- reinstall iTerm nightly with cask;
- try the simple script again;
- try the `tell-iterm2` command again;
- try the plugin again;

All the while hoping that this can clear whatever dictionary cache might exist :)

**Comment by frdmn** [comment]
@marzocchi Okay, i'll try that and report back. 

Another thing I just noticed:

![bildschirmfoto 2015-02-01 um 16 52 46](https://cloud.githubusercontent.com/assets/944459/5992671/d1e8bd06-aa32-11e4-996e-6b454dc40087.png)

The function library of the AppleScript editor only shows the current (actual) version, that I am using.

**Comment by frdmn** [comment]
@marzocchi What the hell :anguished: I just substituted the `tell application "iTerm"` to `tell application "iTerm2"` and tried to run it, and had success. Then i locked back into the AS editor and it automatically reverted back to `tell application "iTerm"`. Tried to run it again, and it still works, also the code from earlier today:

    tell application "iTerm"
      activate
      tty of (current session of current tab of current window) is equal to "/dev/ttys000"
    end tell

The plugin still doesn't work, though. Still the same error message.

**Comment by marzocchi** [comment]
Eh, AppleScript sometimes can be a real mess :)

But are you still getting AppleScript errors (like `Expected “,” but found identifier.`), or shell syntax errors?

It occurred to me that another way to refer to application is by ID, if you are still getting AS errors, what happens if you substitute (in the various files that make up the plugin) `tell application "iTerm"` with `tell application id "com.googlecode.iterm2"`?

**Comment by frdmn** [comment]
Ah sorry, i forgot to pull the latest changes from the `next-iterm` branch which you merged earlier, so the old error was back again, which i didn't noticed at first. 

`tell application id` works for me as well.

Thanks a lot for troubleshooting this issue!

I got one more question, though:

The plugin comes up with an notification if a command runs more than 30 secs (`sleep 31; echo "test"`), but if I try to stderr, I dont get any notifications:

    $ >&2 echo "error"
    $ echo "error >&2

**Comment by frdmn** [comment]
I'll send a PR for the "tell application id" adjustment.

**Comment by marzocchi** [comment]
In general, you should not get a notification if the terminal (and the current shell tab) is active (the assumption is you are looking at it, so you don't need a bubble distracting you).

Then, a failed command always triggers a notification, while a successful command triggers a notification only if it takes more seconds than the value `NOTIFY_COMMAND_COMPLETE_TIMEOUT` (30 by default).

The commands you posted terminate immediately with a status of zero, so there's no need to notify.

Thanks in advance for the PR!
